#png("plot4.png")
par(mfrow = c(2,2))
plot(data[[2]], data[[3]], type = "n", ylab = "Global Active Power (kilowatts)", xlab = "")
lines(x = data[[2]], y = data[[3]])
plot(data[[2]], data[[5]], type = "n", ylab = "Voltage", xlab = "datetime")
lines(x = data[[2]], y = data[[5]])
plot(data[[2]], data[[7]], type = "n", ylab = "Global Active Power (kilowatts)", xlab = "")
lines(x = data[[2]], y = data[[7]])
lines(x = data[[2]], y = data[[8]], col = "red")
lines(x = data[[2]], y = data[[9]], col = "blue")
legend("topright", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1)
plot(data[[2]], data[[4]], type = "n", ylab = "Global Reactive Power (kilowatts)", xlab = "datetime")
lines(x = data[[2]], y = data[[4]])
#dev.off()